Repository PyeongSaeng/PyeongSaeng-BE, pull requests merged in 2025-07, with the labels that each got.

#8 ✨ [Feat] 엔터티 설계
  src/main/java/com/umc/pyeongsaeng/PyeongSaengApplication.java
  src/main/java/com/umc/pyeongsaeng/domain/application/entity/Application.java
  src/main/java/com/umc/pyeongsaeng/domain/application/entity/ApplicationAnswer.java
  src/main/java/com/umc/pyeongsaeng/domain/application/entity/ApplicationQuestion.java
  src/main/java/com/umc/pyeongsaeng/domain/application/enums/ApplicationStatus.java
  src/main/java/com/umc/pyeongsaeng/domain/application/enums/QuestionType.java
  src/main/java/com/umc/pyeongsaeng/domain/auth/entity/RefreshToken.java
  src/main/java/com/umc/pyeongsaeng/domain/company/entity/Company.java
  src/main/java/com/umc/pyeongsaeng/domain/job/entity/JobPost.java
  src/main/java/com/umc/pyeongsaeng/domain/job/entity/JobPostImage.java
  src/main/java/com/umc/pyeongsaeng/domain/senior/entity/SeniorProfile.java
  src/main/java/com/umc/pyeongsaeng/domain/senior/enums/ExperiencePeriod.java
  src/main/java/com/umc/pyeongsaeng/domain/senior/enums/Gender.java
  src/main/java/com/umc/pyeongsaeng/domain/senior/enums/JobType.java
  src/main/java/com/umc/pyeongsaeng/domain/terms/entity/Terms.java
  src/main/java/com/umc/pyeongsaeng/domain/terms/entity/UserTerms.java
  src/main/java/com/umc/pyeongsaeng/domain/user/entity/SocialAccount.java
  src/main/java/com/umc/pyeongsaeng/domain/user/entity/User.java
  src/main/java/com/umc/pyeongsaeng/domain/user/enums/Role.java
  src/main/java/com/umc/pyeongsaeng/domain/user/enums/UserStatus.java
  src/main/java/com/umc/pyeongsaeng/global/common/BaseEntity.java
Labels: ✨ Feature, ♻️ Refactor

#16 🐛 [Fix] CICD Health 안되는 버그 수정
  src/main/java/com/umc/pyeongsaeng/global/common/HealthController.java
  src/main/java/com/umc/pyeongsaeng/global/config/SecurityConfig.java
Labels: 🐛 Fix

#20 🚀[Chore] Swagger 보안 설정 업데이트
  src/main/java/com/umc/pyeongsaeng/domain/auth/controller/AuthController.java
  src/main/java/com/umc/pyeongsaeng/domain/sms/controller/SmsController.java
  src/main/java/com/umc/pyeongsaeng/domain/token/controller/TokenController.java
  src/main/java/com/umc/pyeongsaeng/global/common/HealthController.java
  src/main/java/com/umc/pyeongsaeng/global/config/SwaggerConfig.java
Labels: 🚀 Chore

#21 ✨ [Feat] 기업 신청서 폼 만들기
  src/main/java/com/umc/pyeongsaeng/domain/company/repository/CompanyRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/job/controller/JobPostController.java
  src/main/java/com/umc/pyeongsaeng/domain/job/converter/JobPostConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/job/converter/JobPostImageConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/job/dto/request/CompanyFormFieldRequestDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/job/dto/request/JobPostImageRequestDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/job/dto/request/JobPostRequestDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/job/dto/response/JobPostImageResponseDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/job/dto/response/JobPostResponseDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/job/entity/JobPost.java
  src/main/java/com/umc/pyeongsaeng/domain/job/entity/JobPostField.java
  src/main/java/com/umc/pyeongsaeng/domain/job/entity/JobPostImage.java
  src/main/java/com/umc/pyeongsaeng/domain/job/repository/FormFieldRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/job/repository/JobPostFieldRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/job/repository/JobPostImageRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/job/repository/JobPostRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostCommandService.java
  src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/global/config/SecurityConfig.java
Labels: ✨ Feature, 🐛 Fix, 📝 Docs, ⚙️ Setting

#24 ✨ [Feat] 채용 공고 인덱싱 로직 구현
  .github/workflows/ci-cd.yml
  build.gradle
  src/main/java/com/umc/pyeongsaeng/domain/job/converter/JobPostConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/job/entity/JobPost.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/document/JobPostDocument.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/dto/JobSearchRequest.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/dto/JobSearchResponse.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/enums/JobSortType.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/repository/JobPostSearchRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/repository/JobPostSearchRepositoryCustom.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/repository/JobPostSearchRepositoryImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/pyeongsaeng/global/client/google/GoogleGeocodingClient.java
  src/main/java/com/umc/pyeongsaeng/global/client/google/GoogleGeocodingResult.java
  src/main/java/com/umc/pyeongsaeng/global/config/RestTemplateConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 🚀 Chore, ✨ Feature, 💚 CI/CD

#27 ✨ [Feat] 직선 거리 기반 일자리 추천 기능 구현
  .github/workflows/ci-cd.yml
  build.gradle
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/controller/RecommendationController.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/dto/request/RecommendationRequest.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/dto/request/TravelTimeRequest.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/dto/response/RecommendationResponse.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/dto/response/TravelTimeResponse.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/service/RecommendationService.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/service/TravelTimeService.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/util/DistanceUtil.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/util/TravelTimeUtil.java
  src/main/java/com/umc/pyeongsaeng/domain/senior/entity/SeniorProfile.java
  src/main/java/com/umc/pyeongsaeng/domain/senior/service/SeniorProfileCommandService.java
  src/main/java/com/umc/pyeongsaeng/domain/senior/service/SeniorProfileCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/global/apiPayload/code/status/ErrorStatus.java
  src/main/resources/application.yml
Labels: ✨ Feature, ♻️ Refactor

#29 ✨ [Feat] SMS 전송 기능
  .github/workflows/ci-cd.yml
  build.gradle
  src/main/java/com/umc/pyeongsaeng/domain/sms/service/SmsServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/global/apiPayload/code/status/ErrorStatus.java
  src/main/resources/application.yml
Labels: ✨ Feature, 💚 CI/CD

#33 ✨ [Feat] 기업이 쓴 게시글 조회, Page 리졸버 추가, CORS 프론트엔드 주소 추가
  src/main/java/com/umc/pyeongsaeng/domain/job/controller/JobPostController.java
  src/main/java/com/umc/pyeongsaeng/domain/job/converter/JobPostConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/job/dto/response/JobPostResponseDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/job/repository/JobPostRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryService.java
  src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/pyeongsaeng/global/config/SecurityConfig.java
  src/main/java/com/umc/pyeongsaeng/global/config/WebConfig.java
  src/main/java/com/umc/pyeongsaeng/global/resolvation/annotation/PageNumber.java
  src/main/java/com/umc/pyeongsaeng/global/resolvation/resolver/PageNumberArgumentResolver.java
Labels: ✨ Feature

#37 ✨ [Feat] 검색 구조 변경 및 기능 구현
  .github/workflows/ci-cd.yml
  build.gradle
  src/main/java/com/umc/pyeongsaeng/domain/job/converter/JobPostConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/annotation/GenericElkIndex.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/controller/JobPostSearchController.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/converter/JobPostDocumentConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/document/BaseElkDocument.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/document/JobPostDocument.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/dto/JobSearchRequest.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/dto/JobSearchResponse.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/dto/JobSearchResult.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/elkoperation/ElasticOperationService.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/elkoperation/ElasticOperationServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/listener/ElkIndexCreatorListener.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/repository/JobPostSearchRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/repository/JobPostSearchRepositoryCustom.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/repository/JobPostSearchRepositoryImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/service/JobPostSearchService.java
  src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/senior/service/SeniorProfileCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/pyeongsaeng/global/client/google/GoogleGeocodingClient.java
  src/main/java/com/umc/pyeongsaeng/global/client/google/GoogleGeocodingResult.java
  src/main/java/com/umc/pyeongsaeng/global/config/ElasticsearchConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 🚀 Chore, ✨ Feature, ♻️ Refactor, 💚 CI/CD

#41 ✨ [Feat] 회원 정보 불러오기 및 수정
  .github/workflows/ci-cd.yml
  src/main/java/com/umc/pyeongsaeng/domain/auth/controller/AuthController.java
  src/main/java/com/umc/pyeongsaeng/domain/auth/service/AuthCommandService.java
  src/main/java/com/umc/pyeongsaeng/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/auth/service/AuthQueryService.java
  src/main/java/com/umc/pyeongsaeng/domain/auth/service/AuthQueryServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/auth/service/OAuth2AuthService.java
  src/main/java/com/umc/pyeongsaeng/domain/company/controller/CompanyController.java
  src/main/java/com/umc/pyeongsaeng/domain/company/dto/CompanyRequest.java
  src/main/java/com/umc/pyeongsaeng/domain/company/dto/CompanyResponse.java
  src/main/java/com/umc/pyeongsaeng/domain/company/entity/Company.java
  src/main/java/com/umc/pyeongsaeng/domain/company/service/CompanyCommandService.java
  src/main/java/com/umc/pyeongsaeng/domain/company/service/CompanyCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/company/service/CompanyQueryService.java
  src/main/java/com/umc/pyeongsaeng/domain/company/service/CompanyQueryServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/dto/response/RecommendationResponse.java
  src/main/java/com/umc/pyeongsaeng/domain/senior/entity/SeniorProfile.java
  src/main/java/com/umc/pyeongsaeng/domain/user/controller/UserController.java
  src/main/java/com/umc/pyeongsaeng/domain/user/dto/UserRequest.java
  src/main/java/com/umc/pyeongsaeng/domain/user/dto/UserResponse.java
  src/main/java/com/umc/pyeongsaeng/domain/user/entity/User.java
  src/main/java/com/umc/pyeongsaeng/domain/user/service/UserCommandService.java
  src/main/java/com/umc/pyeongsaeng/domain/user/service/UserCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/user/service/UserQueryService.java
  src/main/java/com/umc/pyeongsaeng/domain/user/service/UserQueryServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/user/service/UserService.java
  src/main/java/com/umc/pyeongsaeng/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/pyeongsaeng/global/config/OAuth2Config.java
  src/main/java/com/umc/pyeongsaeng/global/config/SecurityConfig.java
Labels: ✨ Feature, 🐛 Fix

#48 ✨ [Feat] :docker network 만드는 거 추가
  .github/workflows/ci-cd.yml
Labels: ✨ Feature
