Repository PyeongSaeng/PyeongSaeng-BE, pull requests merged in 2025-08, with the labels that each got.

#50 ✨ [Feat] 채용공고 상세 조회 API 구현
  src/main/java/com/umc/pyeongsaeng/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/job/controller/JobPostController.java
  src/main/java/com/umc/pyeongsaeng/domain/job/converter/JobPostConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/job/converter/JobPostImageConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/job/dto/response/JobPostImageResponseDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/job/dto/response/JobPostResponseDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/service/TravelTimeService.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/util/TravelTimeUtil.java
  src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryService.java
  src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/pyeongsaeng/global/s3/dto/S3DTO.java
  src/main/resources/application-prod.yml
Labels: ✨ Feature

#53 ✨ [Feat] 유저 신청서 작성 플로우
  src/main/java/com/umc/pyeongsaeng/domain/application/controller/ApplicationController.java
  src/main/java/com/umc/pyeongsaeng/domain/application/converter/ApplicationConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/application/dto/request/ApplicationRequestDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/application/dto/response/ApplicationResponseDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/application/entity/ApplicationAnswer.java
  src/main/java/com/umc/pyeongsaeng/domain/application/entity/ApplicationAnswerFile.java
  src/main/java/com/umc/pyeongsaeng/domain/application/repository/ApplicationAnswerFileRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/application/repository/ApplicationAnswerRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/application/repository/ApplicationRepositoryImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationCommandService.java
  src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/job/controller/JobPostController.java
  src/main/java/com/umc/pyeongsaeng/domain/job/converter/FormFieldConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/job/dto/response/JobPostFormFieldResponseDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/job/enums/FieldType.java
  src/main/java/com/umc/pyeongsaeng/domain/job/repository/FormFieldRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryService.java
  src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature, ♻️ Refactor, 📝 Docs

#61 🐛 [Fix] Merge버그 수정
  src/main/java/com/umc/pyeongsaeng/domain/job/controller/JobPostController.java
  src/main/java/com/umc/pyeongsaeng/domain/job/converter/FormFieldConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/job/dto/response/FormFieldResponseDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/job/dto/response/JobPostFormFieldResponseDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryService.java
Labels: 🐛 Fix

#58 ✨[Feat] Open AI 기반 지원서 자동 작성 기능 구현
  src/main/java/com/umc/pyeongsaeng/domain/application/controller/ApplicationController.java
  src/main/java/com/umc/pyeongsaeng/domain/application/controller/OpenAiController.java
  src/main/java/com/umc/pyeongsaeng/domain/application/dto/request/AnswerGenerationRequestDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/application/dto/request/KeywordGenerationRequestDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/application/service/OpenAiService.java
  src/main/java/com/umc/pyeongsaeng/domain/application/service/OpenAiServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/application/util/OpenAiPromptBuilder.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/controller/RecommendationController.java
  src/main/java/com/umc/pyeongsaeng/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/pyeongsaeng/global/config/OpenAiConfig.java
  src/main/resources/application.yml
Labels: ✨ Feature, 📝 Docs, ⚙️ Setting

#62 ✨ [Feat] 검색 응답 구조 개선 및 시니어 좌표 자동 포함 기능 구현
  src/main/java/com/umc/pyeongsaeng/domain/application/repository/ApplicationRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/application/service/event/ApplicationEventListener.java
  src/main/java/com/umc/pyeongsaeng/domain/application/service/event/ApplicationSubmittedEvent.java
  src/main/java/com/umc/pyeongsaeng/domain/job/controller/JobPostController.java
  src/main/java/com/umc/pyeongsaeng/domain/job/converter/JobPostConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/controller/JobPostSearchController.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/converter/JobPostDocumentConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/document/JobPostDocument.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/dto/request/JobSearchRequest.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/dto/response/JobSearchResponse.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/dto/response/JobSearchResult.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/service/JobPostSearchCommandService.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/service/JobPostSearchCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/service/JobPostSearchQueryService.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/service/JobPostSearchQueryServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/senior/controller/SeniorQuestionController.java
  src/main/java/com/umc/pyeongsaeng/domain/senior/dto/request/SeniorQuestionRequestDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/senior/repository/SeniorQuestionAnswerRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/senior/service/SeniorQuestionCommandService.java
  src/main/java/com/umc/pyeongsaeng/domain/senior/service/SeniorQuestionCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/global/apiPayload/code/status/SuccessStatus.java
Labels: ✨ Feature, ♻️ Refactor

#70 ✨ [Feat] 이번주 지원이 많은 공고 GET, 임시저장한 것을 최종저장으로 PUT
  src/main/java/com/umc/pyeongsaeng/domain/application/controller/ApplicationController.java
  src/main/java/com/umc/pyeongsaeng/domain/application/dto/request/ApplicationRequestDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/application/entity/ApplicationAnswer.java
  src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationCommandService.java
  src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/job/controller/JobPostController.java
  src/main/java/com/umc/pyeongsaeng/domain/job/repository/FormFieldRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/job/repository/JobPostRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostCommandService.java
  src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryService.java
  src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryServiceImpl.java
Labels: ✨ Feature

#73 ✨ [Feat] 내 정보 플로우에서 신청서 관리 페이지 API
  src/main/java/com/umc/pyeongsaeng/domain/application/controller/ApplicationController.java
  src/main/java/com/umc/pyeongsaeng/domain/application/converter/ApplicationConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/application/dto/request/ApplicationRequestDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/application/dto/response/ApplicationResponseDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/application/repository/ApplicationRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/application/repository/ApplicationRepositoryCustom.java
  src/main/java/com/umc/pyeongsaeng/domain/application/repository/ApplicationRepositoryImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationCommandService.java
  src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationQueryService.java
  src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationQueryServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/job/controller/JobPostController.java
  src/main/java/com/umc/pyeongsaeng/domain/job/converter/FormFieldConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/job/converter/JobPostConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/job/dto/response/FormFieldResponseDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/job/entity/JobPost.java
  src/main/java/com/umc/pyeongsaeng/domain/job/repository/JobPostRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryService.java
  src/main/java/com/umc/pyeongsaeng/domain/job/service/JobPostQueryServiceImpl.java
Labels: ✨ Feature, 📝 Docs

#74 ✨[Feat] 경력 직무 + 직선거리 기반 추천 기능 구현
  build.gradle
  src/main/java/com/umc/pyeongsaeng/domain/application/dto/request/OpenAiRequestDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/application/dto/response/OpenAiResponseDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/controller/RecommendationController.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/converter/RecommendationConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/dto/request/RecommendationRequestDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/dto/request/TravelTimeRequestDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/dto/response/RecommendationResponse.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/dto/response/RecommendationResponseDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/dto/response/TravelTimeResponseDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/service/RecommendationService.java
  src/main/java/com/umc/pyeongsaeng/domain/job/recommendation/service/RecommendationServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/job/repository/JobPostImageRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/dto/request/JobSearchRequest.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/service/JobPostSearchQueryService.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/service/JobPostSearchQueryServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/senior/enums/JobType.java
Labels: ✨ Feature, ♻️ Refactor, 📝 Docs, ⚙️ Setting

#81 ✨ [Feat] 일자리 저장함 동일 북마크 저장 방지 로직 추가, 신청 클릭 시 updatedAt 갱신
  src/main/java/com/umc/pyeongsaeng/domain/application/controller/ApplicationController.java
  src/main/java/com/umc/pyeongsaeng/domain/application/entity/Application.java
  src/main/java/com/umc/pyeongsaeng/domain/application/repository/ApplicationRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationCommandService.java
  src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/umc/pyeongsaeng/domain/bookmark/dto/response/BookmarkResponseDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/bookmark/entity/Bookmark.java
  src/main/java/com/umc/pyeongsaeng/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/umc/pyeongsaeng/domain/bookmark/service/BookmarkCommandServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/bookmark/service/BookmarkQueryServiceImpl.java
  src/main/java/com/umc/pyeongsaeng/domain/job/search/controller/JobPostSearchController.java
  src/main/java/com/umc/pyeongsaeng/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/umc/pyeongsaeng/global/common/BaseEntity.java
Labels: ✨ Feature, 🐛 Fix

#82 ✨ [Feat] application/me/submitted에서 applicationStatus를 보내도록 수정
  src/main/java/com/umc/pyeongsaeng/domain/application/converter/ApplicationConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/application/dto/response/ApplicationResponseDTO.java
  src/main/java/com/umc/pyeongsaeng/domain/application/repository/ApplicationRepositoryImpl.java
Labels: ✨ Feature

#85 🐛 [Fix] NotBlank채용공고 등록에 잘못 적용한거 수정
  src/main/java/com/umc/pyeongsaeng/domain/application/dto/request/ApplicationRequestDTO.java
Labels: 🐛 Fix

#88 ✨ [Feat] 보호자가 시니어가 제출한 게시글 목록 조회
  src/main/java/com/umc/pyeongsaeng/domain/application/controller/ApplicationController.java
  src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationQueryService.java
  src/main/java/com/umc/pyeongsaeng/domain/application/service/ApplicationQueryServiceImpl.java
Labels: ✨ Feature

#93 ✨ [Feat] 보호자가 시니어가 작성한 제출된 지원서 하나를 상세조회
  src/main/java/com/umc/pyeongsaeng/domain/application/controller/ApplicationController.java
  src/main/java/com/umc/pyeongsaeng/domain/application/converter/ApplicationConverter.java
  src/main/java/com/umc/pyeongsaeng/domain/application/dto/response/ApplicationResponseDTO.java
Labels: ✨ Feature

#99 ♻️ [Refactor] 답변 저장 API PUT 전환
  src/main/java/com/umc/pyeongsaeng/domain/senior/controller/SeniorQuestionController.java
Labels: 🚀 Chore

#103 🐛 [Fix] jobPost 삭제 시 FK 오류 수정
  src/main/java/com/umc/pyeongsaeng/domain/job/entity/JobPost.java
Labels: 🐛 Fix
